### ISSUE TITLE
undefined symbol: OPENSSL_fork_parent

### ISSUE THREAD

**Issue by ssdyue** [tiktok-privacy-innnovation/PETAce#2]
after install petace-0.3.0-py3-none-any.whl, the error occurs:

`>>> import petace.duet`
`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
  `File "/root/miniconda3/lib/python3.10/site-packages/petace/duet/__init__.py", line 15, in <module>`
    `from .vm import VM`
  `File "/root/miniconda3/lib/python3.10/site-packages/petace/duet/vm.py", line 22, in <module>`
    `from petace.duet.pyduet import DuetVM, Instruction`
`ImportError: /root/miniconda3/lib/python3.10/site-packages/petace/duet/pyduet.cpython-310-x86_64-linux-gnu.so: undefined ``symbol: OPENSSL_fork_parent`

openssl version:
`OpenSSL 1.1.1w  11 Sep 2023`

**Comment by PETAce** [comment]
Thanks for using PETAce library!
1. Please make sure the openssl version in your system is consistent with openssl version in python. You can try
```code 
import ssl
print(ssl.OPENSSL_VERSION) 
```
2. The compilation environments we have verified so far are python3.9 and openssl 1.1.1n. We recommend that you recompile using the same environment.
2. In our next release, we will provide a docker environment to ensure that it works, please look forward to it!
